-- Cadastros voluntários de interessados em atuar como corretores parceiros.

create table if not exists public.lucinda_broker_leads (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  full_name text not null check (char_length(full_name) between 3 and 100),
  email text not null check (char_length(email) between 5 and 140),
  phone text not null check (phone ~ '^\d{10,13}$'),
  city text not null check (char_length(city) between 2 and 90),
  state text not null check (state in ('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO')),
  experience_level text not null check (experience_level in ('Quero começar','Atuo há menos de 2 anos','Atuo de 2 a 5 anos','Atuo há mais de 5 anos')),
  professional_status text not null check (professional_status in ('Quero iniciar na área','Corretor autônomo','Trabalho em corretora','Atuo em outra área comercial','Outro perfil')),
  interest_areas text[] not null check (cardinality(interest_areas) between 1 and 4 and interest_areas <@ array['Planos de saúde','Seguros','Odontológico','Plano Pet']::text[]),
  susep_status text not null check (susep_status in ('Tenho registro','Em processo','Ainda não tenho','Não se aplica ao meu momento')),
  message text check (message is null or char_length(message) <= 1000),
  access_city text,
  access_country text,
  consent boolean not null default false,
  status text not null default 'new' check (status in ('new','contacted','archived')),
  created_at timestamptz not null default now()
);

create index if not exists lucinda_broker_leads_created_at_idx on public.lucinda_broker_leads (created_at desc);
create index if not exists lucinda_broker_leads_phone_created_at_idx on public.lucinda_broker_leads (phone, created_at desc);
create index if not exists lucinda_broker_leads_email_created_at_idx on public.lucinda_broker_leads (lower(email), created_at desc);

alter table public.lucinda_broker_leads enable row level security;
revoke all on table public.lucinda_broker_leads from anon, authenticated;
grant insert on table public.lucinda_broker_leads to anon;
grant select on table public.lucinda_broker_leads to authenticated;
grant usage, select on sequence public.lucinda_broker_leads_id_seq to anon;

drop policy if exists "lucinda_public_insert_brokers" on public.lucinda_broker_leads;
create policy "lucinda_public_insert_brokers"
  on public.lucinda_broker_leads
  for insert
  to anon
  with check (
    consent is true
    and status = 'new'
    and char_length(full_name) between 3 and 100
    and char_length(email) between 5 and 140
    and phone ~ '^\d{10,13}$'
    and cardinality(interest_areas) between 1 and 4
  );

drop policy if exists "lucinda_owner_read_brokers" on public.lucinda_broker_leads;
create policy "lucinda_owner_read_brokers"
  on public.lucinda_broker_leads
  for select
  to authenticated
  using (((select auth.jwt()) ->> 'email') = 'mateuscmsilva5@gmail.com');

create or replace function public.enforce_lucinda_broker_cooldown()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if exists (
    select 1 from public.lucinda_broker_leads
    where (phone = new.phone or lower(email) = lower(new.email))
      and created_at > now() - interval '24 hours'
  ) then
    raise exception using errcode = 'P0001', message = 'BROKER_COOLDOWN_24H';
  end if;
  return new;
end;
$$;

revoke all on function public.enforce_lucinda_broker_cooldown() from public, anon, authenticated;
drop trigger if exists lucinda_broker_cooldown_trigger on public.lucinda_broker_leads;
create trigger lucinda_broker_cooldown_trigger
before insert on public.lucinda_broker_leads
for each row execute function public.enforce_lucinda_broker_cooldown();
