-- Estrutura de analytics e contatos do site Lucinda Menezes.
-- Execute este arquivo no SQL Editor do mesmo projeto Supabase usado no teste.

create table if not exists public.lucinda_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in (
    'page_view',
    'whatsapp_click',
    'phone_click',
    'instagram_click',
    'hero_quote_submit',
    'table_quote_submit',
    'contact_form_submit',
    'callback_request'
  )),
  page_path text not null default '/',
  referrer_domain text,
  device_type text not null check (device_type in ('mobile', 'tablet', 'desktop')),
  city text,
  country text,
  created_at timestamptz not null default now()
);

create table if not exists public.lucinda_leads_contacts (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  visitor_name text not null,
  visitor_phone text not null,
  holder_age integer not null check (holder_age between 0 and 120),
  lives text not null,
  plan_type text not null,
  location text not null,
  access_city text,
  access_country text,
  callback_consent boolean not null default false,
  status text not null default 'unread' check (status in ('unread', 'read')),
  created_at timestamptz not null default now()
);

create index if not exists lucinda_analytics_events_created_at_idx
  on public.lucinda_analytics_events (created_at desc);

create index if not exists lucinda_leads_contacts_created_at_idx
  on public.lucinda_leads_contacts (created_at desc);

alter table public.lucinda_analytics_events enable row level security;
alter table public.lucinda_leads_contacts enable row level security;

revoke all on table public.lucinda_analytics_events from anon, authenticated;
revoke all on table public.lucinda_leads_contacts from anon, authenticated;

grant insert on table public.lucinda_analytics_events to anon;
grant insert on table public.lucinda_leads_contacts to anon;
grant select on table public.lucinda_analytics_events to authenticated;
grant select on table public.lucinda_leads_contacts to authenticated;

grant usage, select on sequence public.lucinda_analytics_events_id_seq to anon;
grant usage, select on sequence public.lucinda_leads_contacts_id_seq to anon;

drop policy if exists "lucinda_public_insert_analytics" on public.lucinda_analytics_events;
create policy "lucinda_public_insert_analytics"
  on public.lucinda_analytics_events
  for insert
  to anon
  with check (
    event_name in (
      'page_view',
      'whatsapp_click',
      'phone_click',
      'instagram_click',
      'hero_quote_submit',
      'table_quote_submit',
      'contact_form_submit',
      'callback_request'
    )
    and device_type in ('mobile', 'tablet', 'desktop')
  );

drop policy if exists "lucinda_public_insert_leads" on public.lucinda_leads_contacts;
create policy "lucinda_public_insert_leads"
  on public.lucinda_leads_contacts
  for insert
  to anon
  with check (
    callback_consent is true
    and status = 'unread'
    and char_length(visitor_name) between 3 and 120
    and char_length(visitor_phone) between 10 and 20
  );

drop policy if exists "lucinda_owner_read_analytics" on public.lucinda_analytics_events;
create policy "lucinda_owner_read_analytics"
  on public.lucinda_analytics_events
  for select
  to authenticated
  using (((select auth.jwt()) ->> 'email') = 'mateuscmsilva5@gmail.com');

drop policy if exists "lucinda_owner_read_leads" on public.lucinda_leads_contacts;
create policy "lucinda_owner_read_leads"
  on public.lucinda_leads_contacts
  for select
  to authenticated
  using (((select auth.jwt()) ->> 'email') = 'mateuscmsilva5@gmail.com');
